uploads = []
generated = []

[[outputs]]
id = "6Y5ZtC6KShlgG9-j2QtTT"
uri = "file://src/assets/hospital-bg.jpg"
type = "image"
title = "modern clean hospital interior with teal accents"

[[outputs]]
id = "xKLEKSNOMui0GvXpItxIs"
uri = "file://src/assets/waiting-room.jpg"
type = "image"
title = "modern hospital waiting room clean bright with plants"

[[outputs]]
id = "Zq5WxZpXDJYnDi4gvaEF1"
uri = "file://src/assets/doctor-tablet.jpg"
type = "image"
title = "modern doctor using tablet clean bright medical setting"
